name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out kode dari GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Secrets
        run: |
          echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"  
          echo "Git SHA: $GITHUB_SHA"  
          echo "Image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:$GITHUB_SHA"

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:$GITHUB_SHA .

      # Authenticate dengan Google Cloud menggunakan Service Account
      - name: Google Cloud Authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Push Docker image ke Google Container Registry (GCR)
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/$GCP_PROJECT_ID/fastapi-app:$GITHUB_SHA

      # Deploy ke Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app \
            --image gcr.io/$GCP_PROJECT_ID/fastapi-app:$GITHUB_SHA \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated
