name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Authenticate with Google Cloud using Service Account
      - name: Google Cloud Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure docker for artifact registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/plantgard-registry/plantgard-api:$GITHUB_SHA .

      # Push Docker image to artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/plantgard-registry/plantgard-api:$GITHUB_SHA

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy plantgard-api \
            --image asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/plantgard-registry/plantgard-api:$GITHUB_SHA \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated \
            --max-instances 3 \
            --set-env-vars FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
            --set-env-vars SA_BASE64_KEY=${{ secrets.SA_BASE64_KEY }}
